# Docker-Compose file to run Grafana & InfluxDB using docker
# In this file we are giving the containers names & also exposing the relevant ports i.e 3000, 8086 & 8083
# We are also setting the concerned environmental variable that are needed for our project.

version: "2.0"
services:
  influx:
    image: jaywanii/influxdb:latest
    ports:
     - "8083:8083"
     - "8086:8086"
    environment:
     - INFLUXDB_USER=testsensor
     - INFLUXDB_PASS=testsensor
     - INFLUXDB_NAME=IoTDashboard

  grafana:
    image: jaywanii/grafana:latest
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
     - INFLUXDB_USER=testsensor
     - INFLUXDB_PASS=testsensor
     - INFLUXDB_NAME=IoTDashboard
    ports:
     - "3000:3000"
    links:
     - influx
    depends_on:
     - influx
